name: Regression test
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  regress:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Github Repo Action
      uses: actions/checkout@v4
    - name: Setup apptainer
      uses: eWaterCycle/setup-apptainer@v2.0.0
    - name: Get container from cache
      id: cache-sif
      uses: actions/cache@v3
      with:
        path: .singularity/image.sif
        key: ${{ hashFiles('container.def', 'bin/.container-tag') }}
    - name: Get gems and node files from cache
      id: cache-bundle-npm
      uses: actions/cache@v3
      with:
        path: |
          .home/.gems
          node_modules
        key: ${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('package-lock.json') }}
    - if: ${{ steps.cache-sif.outputs.cache-hit != 'true' }}
      name: Build container
      run: ./bin/build_container
    - name: Setup project
      run: ./bin/setup
    - name: Run IDL tests
      run: ./do idl_test
    - name: Run validator
      run: ./do validate
    - name: Build html documentation for generic_rv64
      run: ./do gen:html[generic_rv64]
    - name: Build PDF documentation for MockCRD-1
      run: ./do gen:crd_pdf[MockCRD-1]
    - name: Build PDF documentation for MC-1
      run: ./do gen:crd_pdf[MC-1]
    - name: Build PDF documentation for RVA Profile Family
      run: ./do gen:profile_pdf[rva]
